# Generated by Django 4.2.2 on 2023-06-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviews",
            name="review_text",
            field=models.TextField(
                help_text="Максимум 1000 символов",
                max_length=1000,
                verbose_name="текст отзыва",
            ),
        ),
        migrations.AlterField(
            model_name="reviews",
            name="type_of_court",
            field=models.CharField(
                choices=[("1", "1"), ("2", "2"), ("3", "3"), ("4", "4"), ("5", "5")],
                default="3",
                help_text="Поставьте оценку отзыва",
                max_length=255,
                verbose_name="оценка",
            ),
        ),
    ]
