# Generated by Django 4.2.2 on 2023-06-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0002_alter_reviews_review_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviews",
            name="created_on",
            field=models.DateField(
                auto_now_add=True, null=True, verbose_name="дата создания"
            ),
        ),
        migrations.AlterField(
            model_name="reviews",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="публикация"),
        ),
    ]
