# Generated by Django 4.2.2 on 2023-06-10 18:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0003_reviews_created_on_alter_reviews_is_published"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reviews",
            old_name="type_of_court",
            new_name="rating",
        ),
        migrations.AlterField(
            model_name="reviews",
            name="created_on",
            field=models.DateField(auto_now_add=True, verbose_name="дата создания"),
        ),
    ]
