# Generated by Django 4.2.2 on 2023-06-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Specialists",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="имя")),
                ("surname", models.CharField(max_length=50, verbose_name="фамилия")),
                ("description", models.TextField(verbose_name="о специалисте")),
                (
                    "person_image",
                    models.ImageField(
                        upload_to="items/",
                        verbose_name="путь до изображения специалиста",
                    ),
                ),
                (
                    "services",
                    models.ManyToManyField(
                        to="services.services", verbose_name="услуги"
                    ),
                ),
            ],
            options={
                "verbose_name": "специалист",
                "verbose_name_plural": "спецаилисты",
            },
        ),
    ]
