# Generated by Django 4.2.2 on 2023-06-10 22:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("specialists", "0002_alter_specialists_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="specialists",
            name="services",
        ),
        migrations.AddField(
            model_name="specialists",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="опубликовано"),
        ),
    ]
