# Generated by Django 4.2.2 on 2023-06-10 14:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="services",
            old_name="decription",
            new_name="description",
        ),
    ]
