# Generated by Django 4.2.2 on 2023-06-10 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0002_rename_decription_services_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="services",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="публикация"),
        ),
        migrations.AddField(
            model_name="services",
            name="main_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="items/",
                verbose_name="путь до изображения товара",
            ),
        ),
        migrations.CreateModel(
            name="ServiceImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="items/", verbose_name="путь до фотографии товара"
                    ),
                ),
                (
                    "service_photos",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="services.services",
                        verbose_name="фотографии товара",
                    ),
                ),
            ],
            options={
                "verbose_name": "фотография изображения",
                "verbose_name_plural": "фотографии изображения",
            },
        ),
    ]
